import { useMemo, useState } from "react";
import { dateLabel, money, percent, staffingOptions } from "./engine";
import { Badge, Button, PageHeading, Panel, Progress } from "./ui";

const riskTone = (band) => band === "Low" ? "success" : band === "Medium" ? "warning" : "danger";

export function Planner({ state, summary, selectedProject, selectedAnalysis, selectProject, addAssignment, createContractorRequest, updateProjectStatus }) {
  const [personId, setPersonId] = useState(state.people[0]?.id || "");
  const [hours, setHours] = useState(8);
  const options = useMemo(() => staffingOptions(selectedProject, state.people, state.contractors, state.assignments), [selectedProject, state.people, state.contractors, state.assignments]);
  const projectAssignments = selectedAnalysis.entries.map((entry) => ({ entry, person: state.people.find((item) => item.id === entry.personId) })).filter((item) => item.person);
  function submitAssignment(event) { event.preventDefault(); addAssignment(selectedProject.id, personId, Number(hours) || 0); }
  return <div className="page">
    <PageHeading eyebrow="Project staffing planner" title="Protect delivery with the right capacity" text="See whether the project has enough weekly hours and skill coverage. Rebalance internal capacity or turn a contractor recommendation into an approved role request."/>
    <div className="project-switcher"><span>Projects</span><div>{summary.projects.map(({ project, analysis }) => <button key={project.id} className={project.id === selectedProject.id ? "selected" : ""} onClick={() => selectProject(project.id)}><i className={riskTone(analysis.band)}></i>{project.name}<b>{analysis.riskScore}</b></button>)}</div></div>
    <section className={`planner-hero ${riskTone(selectedAnalysis.band)}`}><div><p>Selected delivery commitment</p><h2>{selectedProject.name}</h2><span>{selectedProject.client} · deadline {dateLabel(selectedProject.deadline)} · {selectedAnalysis.deadlineDays} days remaining · {selectedProject.status}</span><div className="hero-actions"><Button onClick={() => document.querySelector("#assignment-form")?.scrollIntoView({ behavior: "smooth" })}>Assign internal capacity</Button><Button variant="outline" onClick={() => updateProjectStatus(selectedProject.id, selectedProject.status === "At risk" ? "Active" : "At risk")}>{selectedProject.status === "At risk" ? "Mark active" : "Mark at risk"}</Button></div></div><div className="risk-orb"><div><b>{selectedAnalysis.riskScore}</b><small>staffing risk</small><Badge tone={riskTone(selectedAnalysis.band)}>{selectedAnalysis.band}</Badge></div></div></section>
    <section className="metrics">
      <div className="metric gold"><div><small>Assigned capacity</small><i>◷</i></div><b>{selectedAnalysis.assignedHours}/{selectedProject.targetHours}h</b><span>Weekly assignment target</span></div>
      <div className={`metric ${selectedAnalysis.capacityGap ? "warning" : "success"}`}><div><small>Capacity gap</small><i>!</i></div><b>{selectedAnalysis.capacityGap}h</b><span>Uncovered weekly work</span></div>
      <div className={`metric ${selectedAnalysis.missingSkills.length ? "danger" : "success"}`}><div><small>Missing skills</small><i>◆</i></div><b>{selectedAnalysis.missingSkills.length}</b><span>{selectedAnalysis.missingSkills.length ? selectedAnalysis.missingSkills.join(", ") : "All required skills covered"}</span></div>
      <div className="metric ink"><div><small>Project value</small><i>↗</i></div><b>{money(selectedProject.revenue)}</b><span>Contract revenue</span></div>
    </section>
    <section className="two-col">
      <Panel eyebrow="Current team" title="Assigned people and delivery load"><div className="assignment-list">{projectAssignments.map(({ entry, person }) => <article key={entry.id}><span className="avatar">{person.initials}</span><div><strong>{person.name}</strong><small>{entry.role} · {entry.hours} weekly hours · {person.skills.slice(0, 3).join(", ")}</small></div><Badge tone="blue">{entry.hours}h</Badge></article>)}</div><div className="skill-line"><span>Required skills</span><div>{selectedProject.requiredSkills.map((skill) => <Badge key={skill} tone={selectedAnalysis.missingSkills.includes(skill) ? "danger" : "success"}>{skill}</Badge>)}</div></div></Panel>
      <Panel eyebrow="Staffing risk" title="Why this delivery plan needs attention"><div className="reason-list"><article><span>Capacity coverage</span><b>{percent(selectedProject.targetHours ? selectedAnalysis.assignedHours / selectedProject.targetHours * 100 : 0)}</b>{Progress({ value: selectedProject.targetHours ? selectedAnalysis.assignedHours / selectedProject.targetHours * 100 : 0, tone: selectedAnalysis.capacityGap ? "gold" : "green" })}</article><article><span>Team pressure</span><b>{percent(selectedAnalysis.teamPressure)}</b>{Progress({ value: selectedAnalysis.teamPressure, tone: selectedAnalysis.teamPressure >= 88 ? "red" : "gold" })}</article><article><span>Deadline proximity</span><b>{selectedAnalysis.deadlineDays}d</b><small>{selectedAnalysis.suggestion}</small></article></div></Panel>
    </section>
    <section className="two-col">
      <Panel eyebrow="Internal allocation" title="Add weekly project capacity"><form id="assignment-form" className="assignment-form" onSubmit={submitAssignment}><label>Team member<select value={personId} onChange={(event) => setPersonId(event.target.value)}>{state.people.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.title}</option>)}</select></label><label>Weekly hours<input type="number" min="1" max="40" value={hours} onChange={(event) => setHours(event.target.value)}/></label><Button type="submit">Assign to project</Button></form><p className="helper">Assignments update team utilization, project coverage, delivery risk, and hiring recommendations instantly.</p></Panel>
      <Panel eyebrow="Best-fit coverage" title="Employee and contractor options"><div className="staff-options">{options.slice(0, 5).map((option, index) => <article key={option.id}><span className="avatar">{option.initials}</span><div><strong>{option.name}</strong><small>{option.title} · {Math.round(option.skillMatch * 100)}% skill fit · {Math.round(option.free)}h free</small></div><b>{option.score}</b>{option.kind === "Employee" ? <Button variant="outline" onClick={() => addAssignment(selectedProject.id, option.id, Math.min(8, Math.max(1, Math.floor(option.free))))} disabled={option.free < 1}>Assign</Button> : <Button variant="outline" onClick={() => createContractorRequest(selectedProject, option)}>Draft request</Button>}</article>)}</div></Panel>
    </section>
  </div>;
}
